name: 'Build: User API'

on:
  push:
    branches:
    - main
    paths:
    - 'users/**'
  pull_request:
    branches:
    - main
    paths:
    - 'users/**'

jobs:
  call_dotnet_build:
    uses: fitability/fitability-api/.github/workflows/dotnet-build.yaml@main
    with:
      job_name: 'User API'
      environment: 'dev'
      api_name: 'users'
      api_app_name: 'Fitability.Api.Users'

  call_dotnet_deploy_dev:
    uses: fitability/fitability-api/.github/workflows/dotnet-deploy.yaml@main
    needs: call_dotnet_build
    with:
      job_name: 'User API'
      environment: 'dev'
      api_name: 'users'
      location_code: 'krc'
    secrets:
      azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
      resource_name: '${{ secrets.RESOURCE_NAME }}'
